### ISSUE TITLE
Passage à Google Analytics 4

### ISSUE THREAD

**Issue by julmud** [franck-paul/googleTools#1]
Google va désactiver le support pour Universal Analytics au 1er juillet 2023. D'ici là, il faut passer à Google Analytics 4 (GA4) si on veut continuer à utiliser leurs statistiques.

Pour GA4, il faut mettre le bout de code ci-dessous juste après le tag head de la page d'après leur documentation (où <measurement_id> est un identifiant de stream dans GA4) :
```JavaScript
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<measurement_id>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '<measurement_id>');
</script>
```

**Comment by franck-paul** [comment]
Done
